/**
 * This package provides annotations to allow interface writers to 
 * customize the operations generated by Introduce. The naming 
 * conventions used in this package are based on JSR 181 (the 
 * javax.jws package). 
 */
package edu.umn.msi.cagrid.introduce.interfaces.client;