package gov.nih.nci.cagrid.identifiers.service;

import gov.nih.nci.cagrid.introduce.servicetools.ServiceConfiguration;

import org.globus.wsrf.config.ContainerConfig;
import java.io.File;
import javax.naming.InitialContext;

import org.apache.axis.MessageContext;
import org.globus.wsrf.Constants;


/** 
 * DO NOT EDIT:  This class is autogenerated!
 * 
 * This class holds all service properties which were defined for the service to have
 * access to.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class IdentifiersNAServiceConfiguration implements ServiceConfiguration {

	public static IdentifiersNAServiceConfiguration  configuration = null;
    public String etcDirectoryPath;
    	
	public static IdentifiersNAServiceConfiguration getConfiguration() throws Exception {
		if (IdentifiersNAServiceConfiguration.configuration != null) {
			return IdentifiersNAServiceConfiguration.configuration;
		}
		MessageContext ctx = MessageContext.getCurrentContext();

		String servicePath = ctx.getTargetService();

		String jndiName = Constants.JNDI_SERVICES_BASE_NAME + servicePath + "/serviceconfiguration";
		try {
			javax.naming.Context initialContext = new InitialContext();
			IdentifiersNAServiceConfiguration.configuration = (IdentifiersNAServiceConfiguration) initialContext.lookup(jndiName);
		} catch (Exception e) {
			throw new Exception("Unable to instantiate service configuration.", e);
		}

		return IdentifiersNAServiceConfiguration.configuration;
	}
	

	
	private String identifiersNaPrefix;
	
	private String identifiersNaDbUrl;
	
	private String identifiersNaDbUser;
	
	private String identifiersNaDbPassword;
	
	private String identifiersNaGridSvcUrl;
	
	
    public String getEtcDirectoryPath() {
		return ContainerConfig.getBaseDirectory() + File.separator + etcDirectoryPath;
	}
	
	public void setEtcDirectoryPath(String etcDirectoryPath) {
		this.etcDirectoryPath = etcDirectoryPath;
	}


	
	public String getIdentifiersNaPrefix() {
		return identifiersNaPrefix;
	}
	
	
	public void setIdentifiersNaPrefix(String identifiersNaPrefix) {
		this.identifiersNaPrefix = identifiersNaPrefix;
	}

	
	public String getIdentifiersNaDbUrl() {
		return identifiersNaDbUrl;
	}
	
	
	public void setIdentifiersNaDbUrl(String identifiersNaDbUrl) {
		this.identifiersNaDbUrl = identifiersNaDbUrl;
	}

	
	public String getIdentifiersNaDbUser() {
		return identifiersNaDbUser;
	}
	
	
	public void setIdentifiersNaDbUser(String identifiersNaDbUser) {
		this.identifiersNaDbUser = identifiersNaDbUser;
	}

	
	public String getIdentifiersNaDbPassword() {
		return identifiersNaDbPassword;
	}
	
	
	public void setIdentifiersNaDbPassword(String identifiersNaDbPassword) {
		this.identifiersNaDbPassword = identifiersNaDbPassword;
	}

	
	public String getIdentifiersNaGridSvcUrl() {
		return identifiersNaGridSvcUrl;
	}
	
	
	public void setIdentifiersNaGridSvcUrl(String identifiersNaGridSvcUrl) {
		this.identifiersNaGridSvcUrl = identifiersNaGridSvcUrl;
	}

	
}
