package org.cagrid.tide.replica.context.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import org.cagrid.tide.replica.context.stubs.TideReplicaManagerContextPortType;
import org.cagrid.tide.replica.context.stubs.service.TideReplicaManagerContextServiceAddressingLocator;
import org.cagrid.tide.replica.context.common.TideReplicaManagerContextI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.2
 */
public class TideReplicaManagerContextClient extends TideReplicaManagerContextClientBase implements TideReplicaManagerContextI {	

	public TideReplicaManagerContextClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public TideReplicaManagerContextClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public TideReplicaManagerContextClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public TideReplicaManagerContextClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(TideReplicaManagerContextClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  TideReplicaManagerContextClient client = new TideReplicaManagerContextClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

  public org.oasis.wsrf.lifetime.DestroyResponse destroy(org.oasis.wsrf.lifetime.Destroy params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"destroy");
    return portType.destroy(params);
    }
  }

  public org.oasis.wsrf.lifetime.SetTerminationTimeResponse setTerminationTime(org.oasis.wsrf.lifetime.SetTerminationTime params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"setTerminationTime");
    return portType.setTerminationTime(params);
    }
  }

  public void addReplicaHost(org.apache.axis.message.addressing.EndpointReferenceType tideContextReference) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"addReplicaHost");
    org.cagrid.tide.replica.context.stubs.AddReplicaHostRequest params = new org.cagrid.tide.replica.context.stubs.AddReplicaHostRequest();
    org.cagrid.tide.replica.context.stubs.AddReplicaHostRequestTideContextReference tideContextReferenceContainer = new org.cagrid.tide.replica.context.stubs.AddReplicaHostRequestTideContextReference();
    tideContextReferenceContainer.setEndpointReference(tideContextReference);
    params.setTideContextReference(tideContextReferenceContainer);
    org.cagrid.tide.replica.context.stubs.AddReplicaHostResponse boxedResult = portType.addReplicaHost(params);
    }
  }

  public org.cagrid.tide.descriptor.TideReplicasDescriptor getReplicas() throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getReplicas");
    org.cagrid.tide.replica.context.stubs.GetReplicasRequest params = new org.cagrid.tide.replica.context.stubs.GetReplicasRequest();
    org.cagrid.tide.replica.context.stubs.GetReplicasResponse boxedResult = portType.getReplicas(params);
    return boxedResult.getTideReplicasDescriptor();
    }
  }

  public void reportUnreachableReplicaHost(org.apache.axis.message.addressing.EndpointReferenceType tideContextReference) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"reportUnreachableReplicaHost");
    org.cagrid.tide.replica.context.stubs.ReportUnreachableReplicaHostRequest params = new org.cagrid.tide.replica.context.stubs.ReportUnreachableReplicaHostRequest();
    org.cagrid.tide.replica.context.stubs.ReportUnreachableReplicaHostRequestTideContextReference tideContextReferenceContainer = new org.cagrid.tide.replica.context.stubs.ReportUnreachableReplicaHostRequestTideContextReference();
    tideContextReferenceContainer.setEndpointReference(tideContextReference);
    params.setTideContextReference(tideContextReferenceContainer);
    org.cagrid.tide.replica.context.stubs.ReportUnreachableReplicaHostResponse boxedResult = portType.reportUnreachableReplicaHost(params);
    }
  }

}
