package some.Test;

import some.random.Class1;
import other.random.Class2;

public class AddTest {
  public AddTest() {
    
  }
  
  
  public void foo() {
    
  }
  
  public void bar() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }
  
  public void bar2(int arg1) throws Exception {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }
  
  public void bar3(int arg1,java.lang.String arg2) throws Exception {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }
}