package org.cagrid.workflow.manager.instance.service;

import java.rmi.RemoteException;

import javax.naming.InitialContext;

import org.apache.axis.MessageContext;
import org.cagrid.workflow.manager.service.WorkflowManagerServiceConfiguration;
import org.globus.wsrf.Constants;
import org.globus.wsrf.ResourceHome;


/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * Provides some simple accessors for the Impl.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public abstract class WorkflowManagerInstanceImplBase {
	
	public WorkflowManagerInstanceImplBase() throws RemoteException {
	
	}
	
	public WorkflowManagerServiceConfiguration getConfiguration() throws Exception {
		return WorkflowManagerServiceConfiguration.getConfiguration();
	}
	
	
	public org.cagrid.workflow.manager.instance.service.globus.resource.WorkflowManagerInstanceResourceHome getResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("home");
		return (org.cagrid.workflow.manager.instance.service.globus.resource.WorkflowManagerInstanceResourceHome)resource;
	}

	
	
	
	public org.cagrid.workflow.manager.service.globus.resource.WorkflowManagerServiceResourceHome getWorkflowManagerServiceResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("workflowManagerServiceHome");
		return (org.cagrid.workflow.manager.service.globus.resource.WorkflowManagerServiceResourceHome)resource;
	}
	
	
	protected ResourceHome getResourceHome(String resourceKey) throws Exception {
		MessageContext ctx = MessageContext.getCurrentContext();

		ResourceHome resourceHome = null;
		
		String servicePath = ctx.getTargetService();

		String jndiName = Constants.JNDI_SERVICES_BASE_NAME + servicePath + "/" + resourceKey;
		try {
			javax.naming.Context initialContext = new InitialContext();
			resourceHome = (ResourceHome) initialContext.lookup(jndiName);
		} catch (Exception e) {
			throw new Exception("Unable to instantiate resource home. : " + resourceKey, e);
		}

		return resourceHome;
	}


}

