package org.cagrid.iso21090.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface ISO21090AnalyticalServiceConstantsBase {
	public static final String SERVICE_NS = "http://iso21090.cagrid.org/ISO21090AnalyticalService";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "ISO21090AnalyticalServiceKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "ISO21090AnalyticalServiceResourceProperties");
	
}
