/**
*============================================================================
*  Copyright The Ohio State University Research Foundation, The University of Chicago - 
*	Argonne National Laboratory, Emory University, SemanticBits LLC, and 
*	Ekagra Software Technologies Ltd.
*
*  Distributed under the OSI-approved BSD 3-Clause License.
*  See http://ncip.github.com/cagrid-core/LICENSE.txt for details.
*============================================================================
**/
package org.cagrid.iso21090.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public interface ISO21090AnalyticalServiceI {

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException ;

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException ;

  /**
   * Sends BlNonNull
   *
   * @param blNonNull
   */
  public org.iso._21090.BlNonNull sendBlNonNull(org.iso._21090.BlNonNull blNonNull) throws RemoteException ;

  /**
   * sends
   *
   * @param edText
   */
  public org.iso._21090.EdText sendEdText(org.iso._21090.EdText edText) throws RemoteException ;

  /**
   * Sends Ad
   *
   * @param ad
   */
  public org.iso._21090.Ad sendAd(org.iso._21090.Ad ad) throws RemoteException ;

  /**
   * Sends Bl
   *
   * @param bl
   */
  public org.iso._21090.BL sendBl(org.iso._21090.BL bl) throws RemoteException ;

  /**
   * Sends Cd
   *
   * @param cd
   */
  public org.iso._21090.CD sendCd(org.iso._21090.CD cd) throws RemoteException ;

  /**
   * Sends Ed
   *
   * @param ed
   */
  public org.iso._21090.ED sendEd(org.iso._21090.ED ed) throws RemoteException ;

  /**
   * Sends En
   *
   * @param en
   */
  public org.iso._21090.EN sendEn(org.iso._21090.EN en) throws RemoteException ;

  /**
   * Sends EnOn
   *
   * @param enOn
   */
  public org.iso._21090.EnOn sendEnOn(org.iso._21090.EnOn enOn) throws RemoteException ;

  /**
   * Sends EnPn
   *
   * @param enPn
   */
  public org.iso._21090.EnPn sendEnPn(org.iso._21090.EnPn enPn) throws RemoteException ;

  /**
   * Sends Ii
   *
   * @param ii
   */
  public org.iso._21090.Ii sendIi(org.iso._21090.Ii ii) throws RemoteException ;

  /**
   * Sends IvlInt
   *
   * @param ivlInt
   */
  public org.iso._21090.IVLINT sendIvlInt(org.iso._21090.IVLINT ivlInt) throws RemoteException ;

  /**
   * Sends IvlPq
   *
   * @param ivlPq
   */
  public org.iso._21090.IVLPQ sendIvlPq(org.iso._21090.IVLPQ ivlPq) throws RemoteException ;

  /**
   * Sends IvlReal
   *
   * @param ivlReal
   */
  public org.iso._21090.IVLREAL sendIvlReal(org.iso._21090.IVLREAL ivlReal) throws RemoteException ;

  /**
   * Sends IvlTs
   *
   * @param ivlTs
   */
  public org.iso._21090.IVLTS sendIvlTs(org.iso._21090.IVLTS ivlTs) throws RemoteException ;

  /**
   * Sends Pq
   *
   * @param pq
   */
  public org.iso._21090.PQ sendPq(org.iso._21090.PQ pq) throws RemoteException ;

  /**
   * Sends Real
   *
   * @param real
   */
  public org.iso._21090.Real sendReal(org.iso._21090.Real real) throws RemoteException ;

  /**
   * Sends Sc
   *
   * @param sc
   */
  public org.iso._21090.SC sendSc(org.iso._21090.SC sc) throws RemoteException ;

  /**
   * Sends St
   *
   * @param st
   */
  public org.iso._21090.ST sendSt(org.iso._21090.ST st) throws RemoteException ;

  /**
   * Sends StNt
   *
   * @param stNt
   */
  public org.iso._21090.StNt sendStNt(org.iso._21090.StNt stNt) throws RemoteException ;

  /**
   * Sends Tel
   *
   * @param tel
   */
  public org.iso._21090.TEL sendTel(org.iso._21090.TEL tel) throws RemoteException ;

  /**
   * Sends TelEmail
   *
   * @param telEmail
   */
  public org.iso._21090.TelEmail sendTelEmail(org.iso._21090.TelEmail telEmail) throws RemoteException ;

  /**
   * Sends TelPerson
   *
   * @param telPerson
   */
  public org.iso._21090.TELPerson sendTelPerson(org.iso._21090.TELPerson telPerson) throws RemoteException ;

  /**
   * Sends TelPhone
   *
   * @param telPhone
   */
  public org.iso._21090.TelPhone sendTelPhone(org.iso._21090.TelPhone telPhone) throws RemoteException ;

  /**
   * Sends TelUrl
   *
   * @param telUrl
   */
  public org.iso._21090.TelUrl sendTelUrl(org.iso._21090.TelUrl telUrl) throws RemoteException ;

  /**
   * Sends Ts
   *
   * @param ts
   */
  public org.iso._21090.TS sendTs(org.iso._21090.TS ts) throws RemoteException ;

  /**
   * Sends DSetAd
   *
   * @param dSetAd
   */
  public org.iso._21090.DSetAd sendDSetAd(org.iso._21090.DSetAd dSetAd) throws RemoteException ;

  /**
   * Sends DSetCd
   *
   * @param dSetCd
   */
  public org.iso._21090.DSetCd sendDSetCd(org.iso._21090.DSetCd dSetCd) throws RemoteException ;

  /**
   * Sends DSetII
   *
   * @param dSetII
   */
  public org.iso._21090.DSetII sendDSetII(org.iso._21090.DSetII dSetII) throws RemoteException ;

  public org.iso._21090.DSetTel sendDSetTel(org.iso._21090.DSetTel dSetTel) throws RemoteException ;

  /**
   * Sends Int
   *
   * @param _int
   */
  public org.iso._21090.INT sendInt(org.iso._21090.INT _int) throws RemoteException ;

}

