<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://eclipse.org/bpel/sampleArtifacts" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:wsdl="http://first.cagrid.org/First" xmlns:wsdl1="http://second.cagrid.org/Second" xmlns:wsdl2="http://eclipse.org/bpel/sample" name="ToyWorkflowArtifacts" targetNamespace="http://eclipse.org/bpel/sampleArtifacts">
  <plnk:partnerLinkType name="firstLinkType">
    <plnk:role name="firstService" portType="wsdl:FirstPortType"/>
  </plnk:partnerLinkType>
  <plnk:partnerLinkType name="secondServiceInvocation">
    <plnk:role name="invoker" portType="wsdl1:SecondPortType"/>
  </plnk:partnerLinkType>
    <plnk:partnerLinkType name="ToyWorkflowInput">
    <plnk:role name="UserInvoke" portType="wsdl2:ToyWorkflow"/>
  </plnk:partnerLinkType>
    <plnk:partnerLinkType name="ToyWorkflowResponse">
    <plnk:role name="ToyWorkflowOutput" portType="wsdl2:ToyWorkflowCallback"/>
  </plnk:partnerLinkType>
    <import location="ToyWorkflow.wsdl" namespace="http://eclipse.org/bpel/sample"/>
</definitions>
