package org.cagrid.workflow.manager.instance.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class WorkflowManagerInstanceImpl extends WorkflowManagerInstanceImplBase {

	
	public WorkflowManagerInstanceImpl() throws RemoteException {
		super();
	}
	
  public workflowhelperservice.Status getStatus() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

