/*
* NOTES:
* 1) Many of the tables in the UCSF i2b2 database don't have any primary keys defined at all.  Therfore, this schema has been edited to reflect this change, and allow data to be imported.
* 2) I've added 'COLLATE latin1_general_cs' to every table.  I found a case where the UCSF i2b2 Database has 'test' and 'Test' USER_ID (the primary key) values, which causes problems if your DB isn't case sensitive, which it ISN'T by default under Windows.
* 3) InnoDB engine is used everywhere for proper table locking.
*/

DROP TABLE birn;
CREATE TABLE birn ( C_HLEVEL int NOT NULL, C_FULLNAME varchar(900) NOT NULL, C_NAME varchar(2000) NOT NULL, C_SYNONYM_CD char(1) NOT NULL, C_VISUALATTRIBUTES char(3) NOT NULL, C_TOTALNUM int, C_BASECODE varchar(450), C_METADATAXML text, C_FACTTABLECOLUMN varchar(50) NOT NULL, C_TABLENAME varchar(50) NOT NULL, C_COLUMNNAME varchar(50) NOT NULL, C_COLUMNDATATYPE varchar(50) NOT NULL, C_OPERATOR varchar(10) NOT NULL, C_DIMCODE varchar(900) NOT NULL, C_COMMENT text, C_TOOLTIP varchar(900), UPDATE_DATE datetime, DOWNLOAD_DATE datetime, IMPORT_DATE datetime, SOURCESYSTEM_CD varchar(50), VALUETYPE_CD varchar(50) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE code_lookup;
CREATE TABLE code_lookup ( table_cd varchar(100) NOT NULL, column_cd varchar(100) NOT NULL, code_cd varchar(50) NOT NULL, name_char varchar(650), LOOKUP_BLOB text, UPLOAD_DATE datetime, UPDATE_DATE datetime, DOWNLOAD_DATE datetime, IMPORT_DATE datetime, SOURCESYSTEM_CD varchar(50), UPLOAD_ID int, PRIMARY KEY (table_cd, column_cd, code_cd) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX CL_IDX_NAME_CHAR ON code_lookup;
CREATE INDEX CL_IDX_NAME_CHAR ON code_lookup (name_char);
DROP INDEX CL_IDX_UPLOADID ON code_lookup;
CREATE INDEX CL_IDX_UPLOADID ON code_lookup (UPLOAD_ID);
DROP TABLE concept_dimension;
/* UCSF i2b2 db allows null on ENCODING_CD, doesn't have any primary keys
*/
CREATE TABLE concept_dimension ( CONCEPT_PATH varchar(700) NOT NULL, CONCEPT_CD varchar(50) NOT NULL, NAME_CHAR varchar(2000), CONCEPT_BLOB longtext, UPDATE_DATE date, DOWNLOAD_DATE date, IMPORT_DATE date, SOURCESYSTEM_CD varchar(50), UPLOAD_ID decimal, TABLE_NAME TINYTEXT, ENCODING_CD varchar(25)) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX FK_CONCEPT_DIMEN_ENCODING_DIME ON concept_dimension;
CREATE INDEX FK_CONCEPT_DIMEN_ENCODING_DIME ON concept_dimension (ENCODING_CD);
DROP TABLE crc_db_lookup;
/* TEXT (and it's sub-types) can't be  PK in MYSQL because it has a limit on how many chars will be checked for uniqueness.  The 'solution' is to remove it from the PK definition., as I've done here.
*/
CREATE TABLE crc_db_lookup ( C_DOMAIN_ID TINYTEXT NOT NULL, C_PROJECT_PATH TINYTEXT NOT NULL, C_OWNER_ID TINYTEXT NOT NULL, C_DB_FULLSCHEMA TINYTEXT NOT NULL, C_DB_DATASOURCE TINYTEXT NOT NULL, C_DB_SERVERTYPE TINYTEXT NOT NULL, C_DB_NICENAME TINYTEXT, C_DB_TOOLTIP TINYTEXT, C_COMMENT text, C_ENTRY_DATE datetime, C_CHANGE_DATE datetime, C_STATUS_CD char(1) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE data_request;
CREATE TABLE data_request ( DATA_REQUEST_ID decimal NOT NULL, PROJECT_TITLE varchar(100), IS_RESEARCH_STUDY char(1), RESEARCH_TYPE_CD varchar(3), IS_IRB_APPROVED char(1), IRB_APPROVAL_NO varchar(25), IRB_APPROVAL_TYPE_CD varchar(3), IRB_APPROVAL_DOC varchar(200), IRB_APPROVAL_DATE date, IACUC_APPROVAL_DOC varchar(200), IACUC_APPROVAL_NO varchar(25), IACUC_APPROVAL_DATE date, DATA_REQUEST_REASON varchar(4000), USER_ID varchar(20) NOT NULL, REQUEST_STATUS_CD char(1), REQUEST_DATE date, REQUESTER_NAME varchar(50), REQUESTER_ADDRESS varchar(100), REQUESTER_PHONE decimal, REQUESTER_EMAIL varchar(50), PRIMARY KEY (DATA_REQUEST_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX FK_DATA_REQUEST_IRB_APPROVAL_ ON data_request;
CREATE INDEX FK_DATA_REQUEST_IRB_APPROVAL_ ON data_request (IRB_APPROVAL_TYPE_CD);
DROP INDEX FK_DATA_REQUEST_REQUEST_STATUS ON data_request;
CREATE INDEX FK_DATA_REQUEST_REQUEST_STATUS ON data_request (REQUEST_STATUS_CD);
DROP INDEX FK_DATA_REQUEST_RESEARCH_TYPE ON data_request;
CREATE INDEX FK_DATA_REQUEST_RESEARCH_TYPE ON data_request (RESEARCH_TYPE_CD);
DROP INDEX FK_DATA_REQUEST_USER_INFO ON data_request;
CREATE INDEX FK_DATA_REQUEST_USER_INFO ON data_request (USER_ID);
DROP TABLE datamart_report;
CREATE TABLE datamart_report ( TOTAL_PATIENT int, TOTAL_OBSERVATIONFACT int, TOTAL_EVENT int, REPORT_DATE datetime ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE encoding_dimension;
/*
CREATE TABLE encoding_dimension ( ENCODING_CD varchar(25) NOT NULL, ENCODING_NAME varchar(25) NOT NULL, ENCODING_VERSION decimal(38,2) NOT NULL, ENCODING_DESC varchar(200), CREATE_USER varchar(50), UPDATE_USER varchar(50), CREATE_DATE date, UPDATE_DATE date, PRIMARY KEY (ENCODING_CD) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
*/
CREATE TABLE encoding_dimension (
  ENCODING_CD varchar(25) NOT NULL, ENCODING_NAME varchar(25) NOT NULL,
  ENCODING_VERSION decimal(38,2) NOT NULL, ENCODING_DESC varchar(200),
  CREATE_USER varchar(50), UPDATE_USER varchar(50), 
  CREATE_DATE date, UPDATE_DATE date,
  CONCEPT_PATH varchar(255), CDE_PUBLIC_ID int,
  CDE_VERSION varchar(10), ENCODING_PROJECT_ID int
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX UQ_ENCODING_DIME_ENCODING_NAM ON encoding_dimension;
CREATE UNIQUE INDEX UQ_ENCODING_DIME_ENCODING_NAM ON encoding_dimension (ENCODING_NAME);
create table encoding_project (
 ENCODING_PROJECT_ID int NOT NULL,
 PROJECT_NAME varchar(50),
 PROJECT_VERSION varchar(10),
 PROJECT_ID int,
 ENCODING_SERVICE_ID int,
 PRIMARY KEY (ENCODING_PROJECT_ID) )
ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE encounter_mapping;
CREATE TABLE encounter_mapping ( ENCOUNTER_IDE varchar(200) NOT NULL, ENCOUNTER_IDE_SOURCE varchar(50) NOT NULL, ENCOUNTER_NUM int NOT NULL, PATIENT_IDE varchar(200), PATIENT_IDE_SOURCE varchar(50), ENCOUNTER_IDE_STATUS varchar(50), UPLOAD_DATE datetime, UPDATE_DATE datetime, DOWNLOAD_DATE datetime, IMPORT_DATE datetime, SOURCESYSTEM_CD varchar(50), UPLOAD_ID int, PRIMARY KEY (ENCOUNTER_IDE, ENCOUNTER_IDE_SOURCE) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX EM_IDX_ENCPATH ON encounter_mapping;
CREATE INDEX EM_IDX_ENCPATH ON encounter_mapping (ENCOUNTER_IDE, ENCOUNTER_IDE_SOURCE, PATIENT_IDE, PATIENT_IDE_SOURCE, ENCOUNTER_NUM);
DROP INDEX EM_IDX_UPLOADID ON encounter_mapping;
CREATE INDEX EM_IDX_UPLOADID ON encounter_mapping (UPLOAD_ID);
DROP INDEX EM_ENCNUM_IDX ON encounter_mapping;
CREATE INDEX EM_ENCNUM_IDX ON encounter_mapping (ENCOUNTER_NUM);
DROP TABLE i2b2;
/*
CREATE TABLE i2b2 ( C_HLEVEL decimal NOT NULL, C_FULL_NAME varchar(900) NOT NULL, C_NAME varchar(2000) NOT NULL, C_SYNONYM_CD char(1) NOT NULL, C_VISUALATTRIBUTES char(3) NOT NULL, C_TOTALNUM decimal, C_BASECODE varchar(450), C_METADATAXML longtext, C_FACTTABLECOLUMN varchar(50) NOT NULL, C_TABLENAME varchar(50) NOT NULL, C_COLUMNNAME varchar(50) NOT NULL, C_COLUMNDATATYPE varchar(50) NOT NULL, C_OPERATOR varchar(10) NOT NULL, C_DIMCODE varchar(900) NOT NULL, C_COMMENT longtext, C_TOOLTIP varchar(900), UPDATE_DATE date, DOWNLOAD_DATE date, IMPORT_DATE date, SOURCESYSTEM_CD varchar(50), VALUETYPE_CD varchar(50), CONCEPT_PATH varchar(700) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
*/
CREATE TABLE i2b2 (
  C_HLEVEL decimal NOT NUll, C_FULLNAME varchar(900) not null,
  C_NAME varchar(2000) not null, C_SYNONYM_CD char(1) NOT NULL,
  C_VISUALATTRIBUTES char(3) NOT NULL, C_TOTALNUM decimal,
  C_BASECODE varchar(450), C_METADATAXML longtext,
  C_FACTTABLECOLUMN varchar(50) NOT NULL,
  C_TABLENAME varchar(50) NOT NULL, C_COLUMNNAME varchar(50) NOT NULL,
  C_COLUMNDATATYPE varchar(50) NOT NULL,
  C_OPERATOR varchar(10) NOT NULL, C_DIMCODE varchar(900) NOT NULL,
  C_COMMENT longtext, C_TOOLTIP varchar(900),
  UPDATE_DATE date, DOWNLOAD_DATE date, IMPORT_DATE date,
  SOURCESYSTEM_CD varchar(50), VALUETYPE_CD varchar(50)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;

DROP INDEX FK_I2B2_CONCEPT_DIMENSION ON i2b2;
CREATE INDEX FK_I2B2_CONCEPT_DIMENSION ON i2b2 (CONCEPT_PATH);
DROP TABLE irb_approval_type;
CREATE TABLE irb_approval_type ( IRB_APPROVAL_TYPE_CD varchar(3) NOT NULL, IRB_APPROVAL_TYPE_DESC varchar(50) NOT NULL, CREATE_USER varchar(50), UPDATE_USER varchar(50), CREATE_DATE date, UPDATE_DATE date, PRIMARY KEY (IRB_APPROVAL_TYPE_CD) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE map_aggr_fact;
/* The UCSF i2b2 database doesn't have a primary key on this table at all
CREATE TABLE map_aggr_fact ( CONCEPT_PATH varchar(700) NOT NULL, MAP_ID decimal NOT NULL, VALTYPE_CD varchar(3), TVAL_CHAR TINYTEXT, NVAL_NUM decimal(18,5), QUANTITY_NUM decimal(18,5), UNITS_CD varchar(100), CONFIDENCE_NUM decimal, MAP_DATE date, PRIMARY KEY (CONCEPT_PATH, MAP_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
*/
CREATE TABLE map_aggr_fact ( CONCEPT_PATH varchar(700) NOT NULL, MAP_ID decimal NOT NULL, VALTYPE_CD varchar(3), TVAL_CHAR TINYTEXT, NVAL_NUM decimal(18,5), QUANTITY_NUM decimal(18,5), UNITS_CD varchar(100), CONFIDENCE_NUM decimal, MAP_DATE date) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX FK_MAP_AGGR_FACT_MAP_DIMENSION ON map_aggr_fact;
CREATE INDEX FK_MAP_AGGR_FACT_MAP_DIMENSION ON map_aggr_fact (MAP_ID);
DROP TABLE map_data_fact;
/* The UCSF i2b2 database doesn't have a primary key on this table at all
CREATE TABLE map_data_fact ( ENCOUNTER_NUM decimal NOT NULL, PATIENT_NUM decimal NOT NULL, CONCEPT_CD varchar(50) NOT NULL, PROVIDER_ID varchar(20) NOT NULL, START_DATE date NOT NULL, MODIFIER_CD varchar(100) NOT NULL, CONCEPT_PATH varchar(700) NOT NULL, MAP_ID decimal NOT NULL, VALTYPE_CD varchar(3), TVAL_CHAR TINYTEXT, NVAL_NUM decimal(18,5), VALUEFLAG_CD char(1), QUANTITY_NUM decimal(18,5), UNITS_CD varchar(100), END_DATE date, LOCATION_CD varchar(1) NOT NULL, CONFIDENCE_NUM decimal, OBSERVATION_BLOB longtext, UPDATE_DATE date, DOWNLOAD_DATE date, IMPORT_DATE date, SOURCESYSTEM_CD varchar(50), UPLOAD_ID decimal, OBSERVATION_FACT_ID decimal NOT NULL, MAP_DATE date, PRIMARY KEY (ENCOUNTER_NUM, PATIENT_NUM, CONCEPT_CD, PROVIDER_ID, START_DATE, MODIFIER_CD, CONCEPT_PATH, MAP_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
*/
CREATE TABLE map_data_fact ( ENCOUNTER_NUM decimal NOT NULL, PATIENT_NUM decimal NOT NULL, CONCEPT_CD varchar(50) NOT NULL, PROVIDER_ID varchar(20) NOT NULL, START_DATE date NOT NULL, MODIFIER_CD varchar(100) NOT NULL, CONCEPT_PATH varchar(700) NOT NULL, MAP_ID decimal NOT NULL, VALTYPE_CD varchar(3), TVAL_CHAR TINYTEXT, NVAL_NUM decimal(18,5), VALUEFLAG_CD char(1), QUANTITY_NUM decimal(18,5), UNITS_CD varchar(100), END_DATE date, LOCATION_CD varchar(1) NOT NULL, CONFIDENCE_NUM decimal, OBSERVATION_BLOB longtext, UPDATE_DATE date, DOWNLOAD_DATE date, IMPORT_DATE date, SOURCESYSTEM_CD varchar(50), UPLOAD_ID decimal, OBSERVATION_FACT_ID decimal NOT NULL, MAP_DATE date ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX FK_MAP_DATA_FACT_CONCEPT_DIME ON map_data_fact;
CREATE INDEX FK_MAP_DATA_FACT_CONCEPT_DIME ON map_data_fact (CONCEPT_PATH);
DROP INDEX FK_MAP_DATA_FACT_MAP_DIMENSION ON map_data_fact;
CREATE INDEX FK_MAP_DATA_FACT_MAP_DIMENSION ON map_data_fact (MAP_ID);
DROP INDEX FK_MAP_DATA_FACT_PATIENT_DIME ON map_data_fact;
CREATE INDEX FK_MAP_DATA_FACT_PATIENT_DIME ON map_data_fact (PATIENT_NUM);
DROP TABLE map_dimension;
CREATE TABLE map_dimension ( MAP_ID decimal NOT NULL, MAP_NAME varchar(25) NOT NULL, CONCEPT_PATH varchar(700) NOT NULL, TARGET_ENCODING varchar(25) NOT NULL, MAP_PATH varchar(200) NOT NULL, MAP_DESC varchar(200), IMPORT_DATE date NOT NULL, UPDATE_DATE date, UPLOAD_USER varchar(50), UPDATE_USER varchar(50), LAST_RUN_DATE date, PRIMARY KEY (MAP_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX UQ_MAP_DIMENSION_MAP_NAME ON map_dimension;
CREATE UNIQUE INDEX UQ_MAP_DIMENSION_MAP_NAME ON map_dimension (MAP_NAME);
DROP INDEX FK_MAP_DIMENSION_CONCEPT_DIME ON map_dimension;
CREATE INDEX FK_MAP_DIMENSION_CONCEPT_DIME ON map_dimension (CONCEPT_PATH);
DROP INDEX FK_MAP_DIMENSION_ENCODING_DIME ON map_dimension;
CREATE INDEX FK_MAP_DIMENSION_ENCODING_DIME ON map_dimension (TARGET_ENCODING);
DROP TABLE map_request;
CREATE TABLE map_request ( MAP_REQUEST_ID decimal NOT NULL, CONCEPT_PATH varchar(700) NOT NULL, TARGET_ENCODING varchar(25) NOT NULL, USER_ID varchar(20) NOT NULL, REQUEST_DESC varchar(200), REQUEST_DATE date, MAP_ID decimal, PRIMARY KEY (MAP_REQUEST_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX FK_MAP_REQUEST_CONCEPT_DIMENS ON map_request;
CREATE INDEX FK_MAP_REQUEST_CONCEPT_DIMENS ON map_request (CONCEPT_PATH);
DROP INDEX FK_MAP_REQUEST_MAP_DIMENSION ON map_request;
CREATE INDEX FK_MAP_REQUEST_MAP_DIMENSION ON map_request (MAP_ID);
DROP INDEX FK_MAP_REQUEST_USER_INFO ON map_request;
CREATE INDEX FK_MAP_REQUEST_USER_INFO ON map_request (USER_ID);
DROP INDEX FK_MAP_REQUEST_ENCODING_DIMEN2 ON map_request;
CREATE INDEX FK_MAP_REQUEST_ENCODING_DIMEN2 ON map_request (TARGET_ENCODING);
DROP TABLE observation_fact;
/* The UCSF i2b2 database allows nulls on OBSERVATION_FACT_ID, CONCEPT_PATH, LOCATION_CD, and makes PROVIDER_ID, VALTYPE_CD, VALUEFLAG_CD, and LOCATION_CD a varchar(50)
CREATE TABLE observation_fact ( ENCOUNTER_NUM decimal NOT NULL, PATIENT_NUM decimal NOT NULL, CONCEPT_CD varchar(50) NOT NULL, PROVIDER_ID varchar(20) NOT NULL, START_DATE date NOT NULL, MODIFIER_CD varchar(100) NOT NULL, VALTYPE_CD varchar(3), TVAL_CHAR TINYTEXT, NVAL_NUM decimal(18,5), VALUEFLAG_CD char(1), QUANTITY_NUM decimal(18,5), UNITS_CD varchar(100), END_DATE date, LOCATION_CD varchar(1) NOT NULL, CONFIDENCE_NUM decimal, OBSERVATION_BLOB longtext, UPDATE_DATE date, DOWNLOAD_DATE date, IMPORT_DATE date, SOURCESYSTEM_CD varchar(50), UPLOAD_ID decimal, CONCEPT_PATH varchar(700) NOT NULL, OBSERVATION_FACT_ID decimal NOT NULL, PRIMARY KEY (ENCOUNTER_NUM, CONCEPT_CD, PATIENT_NUM, PROVIDER_ID, START_DATE, MODIFIER_CD) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
*/
CREATE TABLE observation_fact ( ENCOUNTER_NUM decimal NOT NULL, PATIENT_NUM decimal NOT NULL, CONCEPT_CD varchar(50) NOT NULL, PROVIDER_ID varchar(50) NOT NULL, START_DATE date NOT NULL, MODIFIER_CD varchar(100) NOT NULL, VALTYPE_CD varchar(50), TVAL_CHAR TINYTEXT, NVAL_NUM decimal(18,5), VALUEFLAG_CD varchar(50), QUANTITY_NUM decimal(18,5), UNITS_CD varchar(100), END_DATE date, LOCATION_CD varchar(50), CONFIDENCE_NUM decimal, OBSERVATION_BLOB longtext, UPDATE_DATE date, DOWNLOAD_DATE date, IMPORT_DATE date, SOURCESYSTEM_CD varchar(50), UPLOAD_ID decimal, CONCEPT_PATH varchar(700), OBSERVATION_FACT_ID decimal, PRIMARY KEY (ENCOUNTER_NUM, CONCEPT_CD, PATIENT_NUM, PROVIDER_ID, START_DATE, MODIFIER_CD) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX UQ_OBS_F_OBSERVATION_FACT_ID ON observation_fact;
CREATE UNIQUE INDEX UQ_OBS_F_OBSERVATION_FACT_ID ON observation_fact (OBSERVATION_FACT_ID);
DROP INDEX FK_OBS_F_CONCEPT_DIMENSION ON observation_fact;
CREATE INDEX FK_OBS_F_CONCEPT_DIMENSION ON observation_fact (CONCEPT_PATH);
DROP INDEX FK_OBS__F_VISIT_DIMENSION ON observation_fact;
CREATE INDEX FK_OBS__F_VISIT_DIMENSION ON observation_fact (ENCOUNTER_NUM, PATIENT_NUM);
DROP INDEX FK_OBS_F_PATIENT_DIMENSION ON observation_fact;
CREATE INDEX FK_OBS_F_PATIENT_DIMENSION ON observation_fact (PATIENT_NUM);
DROP TABLE ont_db_lookup;
/* TEXT (and it's sub-types) can't be  PK in MYSQL because it has a limit on how many chars will be checked for uniqueness.  The 'solution' is to remove it from the PK definition., as I've done here.
*/
CREATE TABLE ont_db_lookup ( C_DOMAIN_ID TINYTEXT NOT NULL, C_PROJECT_PATH TINYTEXT NOT NULL, C_OWNER_ID TINYTEXT NOT NULL, C_DB_FULLSCHEMA TINYTEXT NOT NULL, C_DB_DATASOURCE TINYTEXT NOT NULL, C_DB_SERVERTYPE TINYTEXT NOT NULL, C_DB_NICENAME TINYTEXT, C_DB_TOOLTIP TINYTEXT, C_COMMENT text, C_ENTRY_DATE datetime, C_CHANGE_DATE datetime, C_STATUS_CD char(1) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE patient_dimension;
CREATE TABLE patient_dimension ( PATIENT_NUM decimal NOT NULL, VITAL_STATUS_CD varchar(3), BIRTH_DATE date, DEATH_DATE date, SEX_CD char(1), AGE_IN_YEARS_NUM decimal, LANGUAGE_CD varchar(50), RACE_CD varchar(50), MARITAL_STATUS_CD varchar(50), RELIGION_CD varchar(50), ZIP_CD varchar(10), STATECITYZIP_PATH varchar(150), PATIENT_BLOB longtext, UPDATE_DATE date, DOWNLOAD_DATE date, IMPORT_DATE date, SOURCESYSTEM_CD varchar(50), UPLOAD_ID decimal, PRIMARY KEY (PATIENT_NUM) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE patient_mapping;
CREATE TABLE patient_mapping ( PATIENT_IDE varchar(200) NOT NULL, PATIENT_IDE_SOURCE varchar(50) NOT NULL, PATIENT_NUM int NOT NULL, PATIENT_IDE_STATUS varchar(50), UPLOAD_DATE datetime, UPDATE_DATE datetime, DOWNLOAD_DATE datetime, IMPORT_DATE datetime, SOURCESYSTEM_CD varchar(50), UPLOAD_ID int, PRIMARY KEY (PATIENT_IDE, PATIENT_IDE_SOURCE) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX PM_IDX_UPLOADID ON patient_mapping;
CREATE INDEX PM_IDX_UPLOADID ON patient_mapping (UPLOAD_ID);
DROP INDEX PM_PATNUM_IDX ON patient_mapping;
CREATE INDEX PM_PATNUM_IDX ON patient_mapping (PATIENT_NUM);
DROP INDEX PM_ENCPNUM_IDX ON patient_mapping;
CREATE INDEX PM_ENCPNUM_IDX ON patient_mapping (PATIENT_IDE, PATIENT_IDE_SOURCE, PATIENT_NUM);
DROP TABLE provider_dimension;
/* The UCSF i2b2 database once again defines no primary keys on this table and makes PROVIDER_ID a varchar(50)
CREATE TABLE provider_dimension ( PROVIDER_PATH varchar(700) NOT NULL, PROVIDER_ID varchar(20) NOT NULL, NAME_CHAR varchar(2000), PROVIDER_BLOB longtext, UPDATE_DATE date, DOWNLOAD_DATE date, IMPORT_DATE date, SOURCESYSTEM_CD varchar(50), UPLOAD_ID int, PRIMARY KEY (PROVIDER_PATH) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
*/
CREATE TABLE provider_dimension ( PROVIDER_PATH varchar(700) NOT NULL, PROVIDER_ID varchar(50) NOT NULL, NAME_CHAR varchar(2000), PROVIDER_BLOB longtext, UPDATE_DATE date, DOWNLOAD_DATE date, IMPORT_DATE date, SOURCESYSTEM_CD varchar(50), UPLOAD_ID int) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE qt_patient_enc_collection;
CREATE TABLE qt_patient_enc_collection ( PATIENT_ENC_COLL_ID int NOT NULL AUTO_INCREMENT, RESULT_INSTANCE_ID int, SET_INDEX int, PATIENT_NUM int, ENCOUNTER_NUM int, PRIMARY KEY (PATIENT_ENC_COLL_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX QT_FK_PESC_RI ON qt_patient_enc_collection;
CREATE INDEX QT_FK_PESC_RI ON qt_patient_enc_collection (RESULT_INSTANCE_ID);
DROP TABLE qt_patient_set_collection;
CREATE TABLE qt_patient_set_collection ( PATIENT_SET_COLL_ID bigint NOT NULL AUTO_INCREMENT, RESULT_INSTANCE_ID int, SET_INDEX int, PATIENT_NUM int, PRIMARY KEY (PATIENT_SET_COLL_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX QT_IDX_QPSC_RIID ON qt_patient_set_collection;
CREATE INDEX QT_IDX_QPSC_RIID ON qt_patient_set_collection (RESULT_INSTANCE_ID);
DROP TABLE qt_query_instance;
CREATE TABLE qt_query_instance ( QUERY_INSTANCE_ID int NOT NULL AUTO_INCREMENT, QUERY_MASTER_ID int, USER_ID varchar(50) NOT NULL, GROUP_ID varchar(50) NOT NULL, BATCH_MODE varchar(50), START_DATE datetime NOT NULL, END_DATE datetime, delete_flag varchar(3), STATUS_TYPE_ID int, PRIMARY KEY (QUERY_INSTANCE_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX QT_FK_QI_STID ON qt_query_instance;
CREATE INDEX QT_FK_QI_STID ON qt_query_instance (STATUS_TYPE_ID);
DROP INDEX QT_IDX_QI_UGID ON qt_query_instance;
CREATE INDEX QT_IDX_QI_UGID ON qt_query_instance (USER_ID, GROUP_ID);
DROP INDEX QT_IDX_QI_MSTARTID ON qt_query_instance;
CREATE INDEX QT_IDX_QI_MSTARTID ON qt_query_instance (QUERY_MASTER_ID, START_DATE);
DROP TABLE qt_query_master;
CREATE TABLE qt_query_master ( QUERY_MASTER_ID int NOT NULL AUTO_INCREMENT, NAME varchar(50) NOT NULL, USER_ID varchar(50) NOT NULL, GROUP_ID varchar(50) NOT NULL, CREATE_DATE datetime NOT NULL, DELETE_DATE datetime, delete_flag varchar(3), REQUEST_XML text, GENERATED_SQL text, I2B2_REQUEST_XML text, PRIMARY KEY (QUERY_MASTER_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX QT_IDX_QM_UGID ON qt_query_master;
CREATE INDEX QT_IDX_QM_UGID ON qt_query_master (USER_ID, GROUP_ID, NAME);
DROP TABLE qt_query_result_instance;
CREATE TABLE qt_query_result_instance ( RESULT_INSTANCE_ID int NOT NULL AUTO_INCREMENT, QUERY_INSTANCE_ID int, RESULT_TYPE_ID int NOT NULL, SET_SIZE int, START_DATE datetime NOT NULL, END_DATE datetime, STATUS_TYPE_ID int NOT NULL, delete_flag varchar(3), PRIMARY KEY (RESULT_INSTANCE_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX QT_FK_QRI_RID ON qt_query_result_instance;
CREATE INDEX QT_FK_QRI_RID ON qt_query_result_instance (QUERY_INSTANCE_ID);
DROP INDEX QT_FK_QRI_RTID ON qt_query_result_instance;
CREATE INDEX QT_FK_QRI_RTID ON qt_query_result_instance (RESULT_TYPE_ID);
DROP INDEX QT_FK_QRI_STID ON qt_query_result_instance;
CREATE INDEX QT_FK_QRI_STID ON qt_query_result_instance (STATUS_TYPE_ID);
DROP TABLE qt_query_result_type;
CREATE TABLE qt_query_result_type ( RESULT_TYPE_ID int NOT NULL, NAME varchar(100), DESCRIPTION varchar(200), PRIMARY KEY (RESULT_TYPE_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE qt_query_status_type;
CREATE TABLE qt_query_status_type ( STATUS_TYPE_ID int NOT NULL, NAME varchar(100), DESCRIPTION varchar(200), PRIMARY KEY (STATUS_TYPE_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE qt_xml_result;
CREATE TABLE qt_xml_result ( XML_RESULT_ID int NOT NULL AUTO_INCREMENT, RESULT_INSTANCE_ID int, XML_VALUE text, PRIMARY KEY (XML_RESULT_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX QT_FK_XMLR_RIID ON qt_xml_result;
CREATE INDEX QT_FK_XMLR_RIID ON qt_xml_result (RESULT_INSTANCE_ID);
DROP TABLE query_criteria;
CREATE TABLE query_criteria ( QUERY_ID decimal NOT NULL, CONCEPT_PATH varchar(700) NOT NULL, IS_VALID char(1), PRIMARY KEY (QUERY_ID, CONCEPT_PATH) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX FK_QUERY_CRITERI_CONCEPT_DIMEN ON query_criteria;
CREATE INDEX FK_QUERY_CRITERI_CONCEPT_DIMEN ON query_criteria (CONCEPT_PATH);
DROP TABLE query_dimension;
CREATE TABLE query_dimension ( QUERY_ID decimal NOT NULL, QUERY_NAME varchar(200) NOT NULL, USER_ID varchar(20) NOT NULL, CREATE_DATE date, UPDATE_DATE date, PRIMARY KEY (QUERY_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX FK_QUERY_DIMENSION_USER_INFO ON query_dimension;
CREATE INDEX FK_QUERY_DIMENSION_USER_INFO ON query_dimension (USER_ID);
DROP TABLE request_status;
CREATE TABLE request_status ( REQUEST_STATUS_CD char(1) NOT NULL, REQUEST_STATUS_DESC varchar(50) NOT NULL, CREATE_USER varchar(50), UPDATE_USER varchar(50), CREATE_DATE date, UPDATE_DATE date, PRIMARY KEY (REQUEST_STATUS_CD) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE research_type;
CREATE TABLE research_type ( RESEARCH_TYPE_CD varchar(3) NOT NULL, RESEARCH_TYPE_DESC varchar(50) NOT NULL, CREATE_USER varchar(50), UPDATE_USER varchar(50), CREATE_DATE date, UPDATE_DATE date, PRIMARY KEY (RESEARCH_TYPE_CD) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE schemes;
CREATE TABLE schemes ( C_KEY varchar(50) NOT NULL, C_NAME varchar(50) NOT NULL, C_DESCRIPTION varchar(100), PRIMARY KEY (C_KEY) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE set_type;
CREATE TABLE set_type ( ID int NOT NULL, NAME varchar(500), CREATE_DATE datetime, PRIMARY KEY (ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE set_upload_status;
CREATE TABLE set_upload_status ( UPLOAD_ID int NOT NULL, SET_TYPE_ID int NOT NULL, SOURCE_CD varchar(50) NOT NULL, NO_OF_RECORD bigint, LOADED_RECORD bigint, DELETED_RECORD bigint, LOAD_DATE datetime NOT NULL, END_DATE datetime, LOAD_STATUS varchar(100), MESSAGE varchar(4000), INPUT_FILE_NAME varchar(500), LOG_FILE_NAME varchar(500), TRANSFORM_NAME varchar(500), PRIMARY KEY (UPLOAD_ID, SET_TYPE_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX FK_UP_SET_TYPE_ID ON set_upload_status;
CREATE INDEX FK_UP_SET_TYPE_ID ON set_upload_status (SET_TYPE_ID);
DROP TABLE source_master;
CREATE TABLE source_master ( SOURCE_CD varchar(50) NOT NULL, DESCRIPTION varchar(300), CREATE_DATE datetime, PRIMARY KEY (SOURCE_CD) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE study_criteria;
CREATE TABLE study_criteria ( DATA_REQUEST_ID decimal NOT NULL, CONCEPT_PATH varchar(700) NOT NULL, ENCODING_REQD varchar(25), PARAMETERS varchar(200), IS_VALID char(1), PRIMARY KEY (DATA_REQUEST_ID, CONCEPT_PATH) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP INDEX FK_STUDY_CRITERI_CONCEPT_DIMEN ON study_criteria;
CREATE INDEX FK_STUDY_CRITERI_CONCEPT_DIMEN ON study_criteria (CONCEPT_PATH);
DROP INDEX FK_STUDY_CRITERI_ENCODING_DIME ON study_criteria;
CREATE INDEX FK_STUDY_CRITERI_ENCODING_DIME ON study_criteria (ENCODING_REQD);
DROP TABLE table_access;
/* No PKs in UCSF...
*/
CREATE TABLE table_access ( C_TABLE_CD varchar(50) NOT NULL, C_TABLE_NAME varchar(50) NOT NULL, C_PROTECTED_ACCESS char(1), C_HLEVEL int NOT NULL, C_FULLNAME varchar(900) NOT NULL, C_NAME varchar(2000) NOT NULL, C_SYNONYM_CD char(1) NOT NULL, C_VISUALATTRIBUTES char(3) NOT NULL, C_TOTALNUM int, C_BASECODE varchar(450), C_METADATAXML text, C_FACTTABLECOLUMN varchar(50) NOT NULL, C_DIMTABLENAME varchar(50) NOT NULL, C_COLUMNNAME varchar(50) NOT NULL, C_COLUMNDATATYPE varchar(50) NOT NULL, C_OPERATOR varchar(10) NOT NULL, C_DIMCODE varchar(900) NOT NULL, C_COMMENT text, C_TOOLTIP varchar(900), C_ENTRY_DATE datetime, C_CHANGE_DATE datetime, C_STATUS_CD char(1) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE upload_status;
CREATE TABLE upload_status ( UPLOAD_ID int NOT NULL AUTO_INCREMENT, UPLOAD_LABEL varchar(500) NOT NULL, USER_ID varchar(100) NOT NULL, SOURCE_CD varchar(50) NOT NULL, NO_OF_RECORD bigint, LOADED_RECORD bigint, DELETED_RECORD bigint, LOAD_DATE datetime NOT NULL, END_DATE datetime, LOAD_STATUS varchar(100), MESSAGE varchar(4000), INPUT_FILE_NAME varchar(500), LOG_FILE_NAME varchar(500), TRANSFORM_NAME varchar(500), PRIMARY KEY (UPLOAD_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE user_info;
/*
* The UCSF i2b2 Database has 'test' and 'Test' USER_ID values, which causes problems if your DB isn't case sensitive.  I've added 'COLLATE latin1_general_cs' to this table
*/
CREATE TABLE user_info ( USER_ID varchar(20) NOT NULL, USER_NAME varchar(50) NOT NULL, USER_TITLE varchar(20), USER_DEPARTMENT varchar(50), USER_ADDRESS varchar(100), USER_PHONE decimal, USER_EMAIL varchar(50), RESEARCH_FOCUS varchar(200), REQUESTER_NAME varchar(50), REQUESTER_TITLE varchar(20), REQUESTER_DEPARTMENT varchar(50), REQUESTER_ADDRESS varchar(100), REQUESTER_PHONE decimal, REQUESTER_EMAIL varchar(50), CREATE_USER varchar(50), UPDATE_USER varchar(50), CREATE_DATE date, UPDATE_DATE date, PRIMARY KEY (USER_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE visit_dimension;
/*
CREATE TABLE visit_dimension ( ENCOUNTER_NUM decimal NOT NULL, PATIENT_NUM decimal NOT NULL, INOUT_CD varchar(5), LOCATION_CD varchar(100), LOCATION_PATH varchar(700), START_DATE date, END_DATE date, VISIT_BLOB longtext, UPDATE_DATE date, DOWNLOAD_DATE date, IMPORT_DATE date, SOURCESYSTEM_CD varchar(50), UPLOAD_ID decimal, PRIMARY KEY (ENCOUNTER_NUM, PATIENT_NUM) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
*/
CREATE TABLE Visit_Dimension ( 
	Encounter_Num  	int NOT NULL,
	Patient_Num    	int NOT NULL,
	Active_status_cd varchar(50) NULL,
	Start_Date     	datetime NULL,
	End_Date       	datetime NULL,
	InOut_Cd       	varchar(50) NULL,
	Location_Cd    	varchar(50) NULL,
    LOCATION_PATH  	VARCHAR(900) NULL,
	Visit_Blob     	text NULL,
	Update_Date    	datetime NULL,
	Download_Date  	datetime NULL,
	Import_Date    	datetime NULL,
	Sourcesystem_cd	varchar(50) NULL ,
    UPLOAD_ID         	INT NULL, 
    CONSTRAINT VISIT_DIMENSION_PK PRIMARY KEY(encounter_num)
	) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE work_db_lookup;
CREATE TABLE work_db_lookup ( C_DOMAIN_ID TINYTEXT NOT NULL, C_PROJECT_PATH TINYTEXT NOT NULL, C_OWNER_ID TINYTEXT NOT NULL, C_DB_FULLSCHEMA TINYTEXT NOT NULL, C_DB_DATASOURCE TINYTEXT NOT NULL, C_DB_SERVERTYPE TINYTEXT NOT NULL, C_DB_NICENAME TINYTEXT, C_DB_TOOLTIP TINYTEXT, C_COMMENT text, C_ENTRY_DATE datetime, C_CHANGE_DATE datetime, C_STATUS_CD char(1) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE workplace;
CREATE TABLE workplace ( C_NAME TINYTEXT NOT NULL, C_USER_ID TINYTEXT NOT NULL, C_GROUP_ID TINYTEXT NOT NULL, C_SHARE_ID TINYTEXT, C_INDEX TINYTEXT NOT NULL, C_PARENT_INDEX TINYTEXT, C_VISUALATTRIBUTES char(3) NOT NULL, C_PROTECTED_ACCESS char(1), C_TOOLTIP TINYTEXT, C_WORK_XML text, C_WORK_XML_SCHEMA text, C_WORK_XML_I2B2_TYPE TINYTEXT, C_ENTRY_DATE datetime, C_CHANGE_DATE datetime, C_STATUS_CD char(1) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;
DROP TABLE workplace_access;
CREATE TABLE workplace_access ( C_TABLE_CD TINYTEXT NOT NULL, C_TABLE_NAME TINYTEXT NOT NULL, C_PROTECTED_ACCESS char(1), C_HLEVEL int NOT NULL, C_NAME TINYTEXT NOT NULL, C_USER_ID TINYTEXT NOT NULL, C_GROUP_ID TINYTEXT NOT NULL, C_SHARE_ID TINYTEXT, C_INDEX TINYTEXT NOT NULL, C_PARENT_INDEX TINYTEXT, C_VISUALATTRIBUTES char(3) NOT NULL, C_TOOLTIP TINYTEXT, C_ENTRY_DATE datetime, C_CHANGE_DATE datetime, C_STATUS_CD char(1) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_general_cs;

