/**
*============================================================================
*  The Ohio State University Research Foundation, Emory University,
*  the University of Minnesota Supercomputing Institute
*
*  Distributed under the OSI-approved BSD 3-Clause License.
*  See http://ncip.github.com/cagrid-grid-incubation/LICENSE.txt for details.
*============================================================================
**/
/**
*============================================================================
*============================================================================
**/
package gov.nih.nci.cagrid.identifiers.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface IdentifiersNAServiceConstantsBase {
	public static final String SERVICE_NS = "http://identifiers.cagrid.nci.nih.gov/IdentifiersNAService";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "IdentifiersNAServiceKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "IdentifiersNAServiceResourceProperties");
	
}
