package org.cagrid.introduce.service5.service.globus;

import org.cagrid.introduce.service5.service.Service5Impl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the Service5Impl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.1
 * 
 */
public class Service5ProviderImpl{
	
	Service5Impl impl;
	
	public Service5ProviderImpl() throws RemoteException {
		impl = new Service5Impl();
	}
	

    public org.cagrid.introduce.service5.stubs.CheckStringAndItsLengthResponse checkStringAndItsLength(org.cagrid.introduce.service5.stubs.CheckStringAndItsLengthRequest params) throws RemoteException {
    org.cagrid.introduce.service5.stubs.CheckStringAndItsLengthResponse boxedResult = new org.cagrid.introduce.service5.stubs.CheckStringAndItsLengthResponse();
    boxedResult.setResponse(impl.checkStringAndItsLength(params.getStringAndItsLenght().getStringAndItsLenght()));
    return boxedResult;
  }

}
