package org.cagrid.helloworld.service.globus;


import java.rmi.RemoteException;
import javax.security.auth.Subject;
import javax.xml.namespace.QName;
import javax.xml.rpc.handler.MessageContext;

import org.globus.wsrf.impl.security.authorization.exceptions.AuthorizationException;
import org.globus.wsrf.impl.security.authorization.exceptions.CloseException;
import org.globus.wsrf.impl.security.authorization.exceptions.InitializeException;
import org.globus.wsrf.impl.security.authorization.exceptions.InvalidPolicyException;
import org.globus.wsrf.security.authorization.PDP;
import org.globus.wsrf.security.authorization.PDPConfig;
import org.w3c.dom.Node;


/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This is a PDP for use with the globus authorization callout.
 * This class will have a authorize<methodName> method for each method on this grid service.
 * The method is responsibe for making any authorization callouts required to satisfy the 
 * authorization requirements placed on each method call.  Each method will either return
 * apon a successful authorization or will throw an exception apon a failed authorization.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class HelloWorldSecureAuthorization implements PDP {

	public static final String SERVICE_NAMESPACE = "http://helloworld.cagrid.org/HelloWorldSecure";
	
	
	public HelloWorldSecureAuthorization() {
	}
	
	protected String getServiceNamespace(){
		return SERVICE_NAMESPACE;
	}
	
	public static String getCallerIdentity() {
		String caller = org.globus.wsrf.security.SecurityManager.getManager().getCaller();
		if ((caller == null) || (caller.equals("<anonymous>"))) {
			return null;
		} else {
			return caller;
		}
	}
					
	public static void authorizeGetMultipleResourceProperties() throws RemoteException {
		
		
	}
					
	public static void authorizeGetResourceProperty() throws RemoteException {
		
		
	}
					
	public static void authorizeQueryResourceProperties() throws RemoteException {
		
		
	}
					
	public static void authorizeGetServiceSecurityMetadata() throws RemoteException {
		
		
	}
	
    public static final String gridGrouperAuthorizeNewMethodSecure = "<ns1:MembershipExpression ns1:logicRelation=\"AND\" xmlns:ns1=\"http://cagrid.nci.nih.gov/1/GridGrouper\">"
		 + " <ns1:MembershipQuery ns1:MembershipStatus=\"MEMBER_OF\">"
		 + "  <ns1:GroupIdentifier>"
		 + "   <ns1:gridGrouperURL>https://grouper.training.cagrid.org:8443/wsrf/services/cagrid/GridGrouper</ns1:gridGrouperURL>"
		 + "   <ns1:GroupName>Training:Trainees</ns1:GroupName>"
		 + "  </ns1:GroupIdentifier>"
		 + " </ns1:MembershipQuery>"
		 + "</ns1:MembershipExpression>";				
	public static void authorizeNewMethodSecure() throws RemoteException {
		
		/**************** Start Grid Grouper Authorization *****************/
		String gridIdentity = getCallerIdentity();
		
		boolean isMember=false;
		if(gridIdentity!=null){
			try{
				isMember=gov.nih.nci.cagrid.gridgrouper.client.GridGrouperClientUtils.isMember(gridGrouperAuthorizeNewMethodSecure,gridIdentity);
			}catch(Exception e){
				e.printStackTrace();
				throw new java.rmi.RemoteException("Error determining if caller is authorized to perform request");
			}
		}
		if(!isMember){
			throw new java.rmi.RemoteException("Not authorized to perform request");
		}
		/************** End Grid Grouper Authorization ***************/
		
	}
	
	
	public boolean isPermitted(Subject peerSubject, MessageContext context, QName operation)
		throws AuthorizationException {
		
		if(!operation.getNamespaceURI().equals(getServiceNamespace())){
		  return false;
		}
		if(operation.getLocalPart().equals("getMultipleResourceProperties")){
			try{
				authorizeGetMultipleResourceProperties();
				return true;
			} catch (Exception e){
				e.printStackTrace();
				return false;
			}
		} else if(operation.getLocalPart().equals("getResourceProperty")){
			try{
				authorizeGetResourceProperty();
				return true;
			} catch (Exception e){
				e.printStackTrace();
				return false;
			}
		} else if(operation.getLocalPart().equals("queryResourceProperties")){
			try{
				authorizeQueryResourceProperties();
				return true;
			} catch (Exception e){
				e.printStackTrace();
				return false;
			}
		} else if(operation.getLocalPart().equals("getServiceSecurityMetadata")){
			try{
				authorizeGetServiceSecurityMetadata();
				return true;
			} catch (Exception e){
				e.printStackTrace();
				return false;
			}
		} else if(operation.getLocalPart().equals("newMethodSecure")){
			try{
				authorizeNewMethodSecure();
				return true;
			} catch (Exception e){
				e.printStackTrace();
				return false;
			}
		} 		
		return false;
	}
	

	public Node getPolicy(Node query) throws InvalidPolicyException {
		return null;
	}


	public String[] getPolicyNames() {
		return null;
	}


	public Node setPolicy(Node policy) throws InvalidPolicyException {
		return null;
	}


	public void close() throws CloseException {


	}


	public void initialize(PDPConfig config, String name, String id) throws InitializeException {

	}
	
	
}
