/**
*============================================================================
*  The Ohio State University Research Foundation, Emory University,
*  the University of Minnesota Supercomputing Institute
*
*  Distributed under the OSI-approved BSD 3-Clause License.
*  See http://ncip.github.com/cagrid-grid-incubation/LICENSE.txt for details.
*============================================================================
**/
/**
*============================================================================
*============================================================================
**/
package org.cagrid.gaards.csm.service.globus;

import java.rmi.RemoteException;

import org.cagrid.gaards.csm.service.CSMImpl;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the CSMImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class CSMProviderImpl{
	
	CSMImpl impl;
	
	public CSMProviderImpl() throws RemoteException {
		impl = new CSMImpl();
	}
	

    public org.cagrid.gaards.csm.stubs.GetApplicationsResponse getApplications(org.cagrid.gaards.csm.stubs.GetApplicationsRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault {
    org.cagrid.gaards.csm.stubs.GetApplicationsResponse boxedResult = new org.cagrid.gaards.csm.stubs.GetApplicationsResponse();
    boxedResult.setApplication(impl.getApplications(params.getApplicationSearchCriteria().getApplicationSearchCriteria()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.CreateApplicationResponse createApplication(org.cagrid.gaards.csm.stubs.CreateApplicationRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.CreateApplicationResponse boxedResult = new org.cagrid.gaards.csm.stubs.CreateApplicationResponse();
    boxedResult.setApplication(impl.createApplication(params.getApplication().getApplication()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.RemoveApplicationResponse removeApplication(org.cagrid.gaards.csm.stubs.RemoveApplicationRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.RemoveApplicationResponse boxedResult = new org.cagrid.gaards.csm.stubs.RemoveApplicationResponse();
    impl.removeApplication(params.getApplicationId());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.CreateProtectionElementResponse createProtectionElement(org.cagrid.gaards.csm.stubs.CreateProtectionElementRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.CreateProtectionElementResponse boxedResult = new org.cagrid.gaards.csm.stubs.CreateProtectionElementResponse();
    boxedResult.setProtectionElement(impl.createProtectionElement(params.getPe().getProtectionElement()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.GetProtectionElementsResponse getProtectionElements(org.cagrid.gaards.csm.stubs.GetProtectionElementsRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.GetProtectionElementsResponse boxedResult = new org.cagrid.gaards.csm.stubs.GetProtectionElementsResponse();
    boxedResult.setProtectionElement(impl.getProtectionElements(params.getCriteria().getProtectionElementSearchCriteria()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.ModifyProtectionElementResponse modifyProtectionElement(org.cagrid.gaards.csm.stubs.ModifyProtectionElementRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.ModifyProtectionElementResponse boxedResult = new org.cagrid.gaards.csm.stubs.ModifyProtectionElementResponse();
    boxedResult.setProtectionElement(impl.modifyProtectionElement(params.getProtectionElement().getProtectionElement()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.RemoveProtectionElementResponse removeProtectionElement(org.cagrid.gaards.csm.stubs.RemoveProtectionElementRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.RemoveProtectionElementResponse boxedResult = new org.cagrid.gaards.csm.stubs.RemoveProtectionElementResponse();
    impl.removeProtectionElement(params.getProtectionElementId());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.CreateProtectionGroupResponse createProtectionGroup(org.cagrid.gaards.csm.stubs.CreateProtectionGroupRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.CreateProtectionGroupResponse boxedResult = new org.cagrid.gaards.csm.stubs.CreateProtectionGroupResponse();
    boxedResult.setProtectionGroup(impl.createProtectionGroup(params.getPg().getProtectionGroup()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.GetProtectionGroupsResponse getProtectionGroups(org.cagrid.gaards.csm.stubs.GetProtectionGroupsRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.GetProtectionGroupsResponse boxedResult = new org.cagrid.gaards.csm.stubs.GetProtectionGroupsResponse();
    boxedResult.setProtectionGroup(impl.getProtectionGroups(params.getCriteria().getProtectionGroupSearchCriteria()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.ModifyProtectionGroupResponse modifyProtectionGroup(org.cagrid.gaards.csm.stubs.ModifyProtectionGroupRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.ModifyProtectionGroupResponse boxedResult = new org.cagrid.gaards.csm.stubs.ModifyProtectionGroupResponse();
    boxedResult.setProtectionGroup(impl.modifyProtectionGroup(params.getPg().getProtectionGroup()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.RemoveProtectionGroupResponse removeProtectionGroup(org.cagrid.gaards.csm.stubs.RemoveProtectionGroupRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.RemoveProtectionGroupResponse boxedResult = new org.cagrid.gaards.csm.stubs.RemoveProtectionGroupResponse();
    impl.removeProtectionGroup(params.getProtectionGroupId());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.AssignProtectionElementsResponse assignProtectionElements(org.cagrid.gaards.csm.stubs.AssignProtectionElementsRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.AssignProtectionElementsResponse boxedResult = new org.cagrid.gaards.csm.stubs.AssignProtectionElementsResponse();
    impl.assignProtectionElements(params.getProtectionGroupId(),params.getProtectionElements());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.UnassignProtectionElementsResponse unassignProtectionElements(org.cagrid.gaards.csm.stubs.UnassignProtectionElementsRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.UnassignProtectionElementsResponse boxedResult = new org.cagrid.gaards.csm.stubs.UnassignProtectionElementsResponse();
    impl.unassignProtectionElements(params.getProtectionGroupId(),params.getProtectionElements());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.GetProtectionElementsAssignedToProtectionGroupResponse getProtectionElementsAssignedToProtectionGroup(org.cagrid.gaards.csm.stubs.GetProtectionElementsAssignedToProtectionGroupRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.GetProtectionElementsAssignedToProtectionGroupResponse boxedResult = new org.cagrid.gaards.csm.stubs.GetProtectionElementsAssignedToProtectionGroupResponse();
    boxedResult.setProtectionElement(impl.getProtectionElementsAssignedToProtectionGroup(params.getProtectionGroupId()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.AssignProtectionGroupResponse assignProtectionGroup(org.cagrid.gaards.csm.stubs.AssignProtectionGroupRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.AssignProtectionGroupResponse boxedResult = new org.cagrid.gaards.csm.stubs.AssignProtectionGroupResponse();
    impl.assignProtectionGroup(params.getParentProtectionGroupId(),params.getChildProtectionGroupId());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.UnassignProtectionGroupResponse unassignProtectionGroup(org.cagrid.gaards.csm.stubs.UnassignProtectionGroupRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.UnassignProtectionGroupResponse boxedResult = new org.cagrid.gaards.csm.stubs.UnassignProtectionGroupResponse();
    impl.unassignProtectionGroup(params.getParentProtectionGroupId(),params.getChildProtectionGroupId());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.GetChildProtectionGroupsResponse getChildProtectionGroups(org.cagrid.gaards.csm.stubs.GetChildProtectionGroupsRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.GetChildProtectionGroupsResponse boxedResult = new org.cagrid.gaards.csm.stubs.GetChildProtectionGroupsResponse();
    boxedResult.setProtectionGroup(impl.getChildProtectionGroups(params.getProtectionGroupId()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.GetGroupsResponse getGroups(org.cagrid.gaards.csm.stubs.GetGroupsRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.GetGroupsResponse boxedResult = new org.cagrid.gaards.csm.stubs.GetGroupsResponse();
    boxedResult.setGroup(impl.getGroups(params.getCriteria().getGroupSearchCriteria()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.LinkRemoteGroupResponse linkRemoteGroup(org.cagrid.gaards.csm.stubs.LinkRemoteGroupRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.LinkRemoteGroupResponse boxedResult = new org.cagrid.gaards.csm.stubs.LinkRemoteGroupResponse();
    boxedResult.setRemoteGroup(impl.linkRemoteGroup(params.getReq().getLinkRemoteGroupRequest()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.UnlinkRemoteGroupResponse unlinkRemoteGroup(org.cagrid.gaards.csm.stubs.UnlinkRemoteGroupRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.UnlinkRemoteGroupResponse boxedResult = new org.cagrid.gaards.csm.stubs.UnlinkRemoteGroupResponse();
    impl.unlinkRemoteGroup(params.getApplicationId(),params.getGroupId());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.CreateGroupResponse createGroup(org.cagrid.gaards.csm.stubs.CreateGroupRequest params) throws RemoteException {
    org.cagrid.gaards.csm.stubs.CreateGroupResponse boxedResult = new org.cagrid.gaards.csm.stubs.CreateGroupResponse();
    boxedResult.setLocalGroup(impl.createGroup(params.getGrp().getLocalGroup()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.RemoveGroupResponse removeGroup(org.cagrid.gaards.csm.stubs.RemoveGroupRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.RemoveGroupResponse boxedResult = new org.cagrid.gaards.csm.stubs.RemoveGroupResponse();
    impl.removeGroup(params.getGroupId());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.ModifyGroupResponse modifyGroup(org.cagrid.gaards.csm.stubs.ModifyGroupRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.ModifyGroupResponse boxedResult = new org.cagrid.gaards.csm.stubs.ModifyGroupResponse();
    boxedResult.setLocalGroup(impl.modifyGroup(params.getGrp().getLocalGroup()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.AddUsersToGroupResponse addUsersToGroup(org.cagrid.gaards.csm.stubs.AddUsersToGroupRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.AddUsersToGroupResponse boxedResult = new org.cagrid.gaards.csm.stubs.AddUsersToGroupResponse();
    impl.addUsersToGroup(params.getGroupId(),params.getUsers());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.RemoveUsersFromGroupResponse removeUsersFromGroup(org.cagrid.gaards.csm.stubs.RemoveUsersFromGroupRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault {
    org.cagrid.gaards.csm.stubs.RemoveUsersFromGroupResponse boxedResult = new org.cagrid.gaards.csm.stubs.RemoveUsersFromGroupResponse();
    impl.removeUsersFromGroup(params.getGroupId(),params.getUsers());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.GetUsersInGroupResponse getUsersInGroup(org.cagrid.gaards.csm.stubs.GetUsersInGroupRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.GetUsersInGroupResponse boxedResult = new org.cagrid.gaards.csm.stubs.GetUsersInGroupResponse();
    boxedResult.setResponse(impl.getUsersInGroup(params.getGroupId()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.CreatePrivilegeResponse createPrivilege(org.cagrid.gaards.csm.stubs.CreatePrivilegeRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.CreatePrivilegeResponse boxedResult = new org.cagrid.gaards.csm.stubs.CreatePrivilegeResponse();
    boxedResult.setPrivilege(impl.createPrivilege(params.getPrivilege().getPrivilege()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.GetPrivilegesResponse getPrivileges(org.cagrid.gaards.csm.stubs.GetPrivilegesRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.GetPrivilegesResponse boxedResult = new org.cagrid.gaards.csm.stubs.GetPrivilegesResponse();
    boxedResult.setPrivilege(impl.getPrivileges(params.getCriteria().getPrivilegeSearchCriteria()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.RemovePrivilegeResponse removePrivilege(org.cagrid.gaards.csm.stubs.RemovePrivilegeRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.RemovePrivilegeResponse boxedResult = new org.cagrid.gaards.csm.stubs.RemovePrivilegeResponse();
    impl.removePrivilege(params.getPrivilegeId());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.ModifyPrivilegeResponse modifyPrivilege(org.cagrid.gaards.csm.stubs.ModifyPrivilegeRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.ModifyPrivilegeResponse boxedResult = new org.cagrid.gaards.csm.stubs.ModifyPrivilegeResponse();
    boxedResult.setPrivilege(impl.modifyPrivilege(params.getPrivilege().getPrivilege()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.CreateRoleResponse createRole(org.cagrid.gaards.csm.stubs.CreateRoleRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.CreateRoleResponse boxedResult = new org.cagrid.gaards.csm.stubs.CreateRoleResponse();
    boxedResult.setRole(impl.createRole(params.getRole().getRole()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.GetRolesResponse getRoles(org.cagrid.gaards.csm.stubs.GetRolesRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.GetRolesResponse boxedResult = new org.cagrid.gaards.csm.stubs.GetRolesResponse();
    boxedResult.setRole(impl.getRoles(params.getCriteria().getRoleSearchCriteria()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.ModifyRoleResponse modifyRole(org.cagrid.gaards.csm.stubs.ModifyRoleRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.ModifyRoleResponse boxedResult = new org.cagrid.gaards.csm.stubs.ModifyRoleResponse();
    boxedResult.setRole(impl.modifyRole(params.getRole().getRole()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.RemoveRoleResponse removeRole(org.cagrid.gaards.csm.stubs.RemoveRoleRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.RemoveRoleResponse boxedResult = new org.cagrid.gaards.csm.stubs.RemoveRoleResponse();
    impl.removeRole(params.getRoleId());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.SetPrivilegesForRoleResponse setPrivilegesForRole(org.cagrid.gaards.csm.stubs.SetPrivilegesForRoleRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.SetPrivilegesForRoleResponse boxedResult = new org.cagrid.gaards.csm.stubs.SetPrivilegesForRoleResponse();
    impl.setPrivilegesForRole(params.getRoleId(),params.getPrivs());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.GetPrivilegesForRoleResponse getPrivilegesForRole(org.cagrid.gaards.csm.stubs.GetPrivilegesForRoleRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.GetPrivilegesForRoleResponse boxedResult = new org.cagrid.gaards.csm.stubs.GetPrivilegesForRoleResponse();
    boxedResult.setPrivilege(impl.getPrivilegesForRole(params.getRoleId()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.GrantGroupPermissionResponse grantGroupPermission(org.cagrid.gaards.csm.stubs.GrantGroupPermissionRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.GrantGroupPermissionResponse boxedResult = new org.cagrid.gaards.csm.stubs.GrantGroupPermissionResponse();
    impl.grantGroupPermission(params.getGroupId(),params.getRoleId(),params.getProtectionGroupId());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.RevokeGroupPermissionResponse revokeGroupPermission(org.cagrid.gaards.csm.stubs.RevokeGroupPermissionRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.RevokeGroupPermissionResponse boxedResult = new org.cagrid.gaards.csm.stubs.RevokeGroupPermissionResponse();
    impl.revokeGroupPermission(params.getGroupId(),params.getRoleId(),params.getProtectionGroupId());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.GrantUserPermissionResponse grantUserPermission(org.cagrid.gaards.csm.stubs.GrantUserPermissionRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.GrantUserPermissionResponse boxedResult = new org.cagrid.gaards.csm.stubs.GrantUserPermissionResponse();
    impl.grantUserPermission(params.getUserIdentity(),params.getRoleId(),params.getProtectionGroupId());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.RevokeUserPermissionResponse revokeUserPermission(org.cagrid.gaards.csm.stubs.RevokeUserPermissionRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.RevokeUserPermissionResponse boxedResult = new org.cagrid.gaards.csm.stubs.RevokeUserPermissionResponse();
    impl.revokeUserPermission(params.getUserIdentity(),params.getRoleId(),params.getProtectionGroupId());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.GetPermissionsForUserResponse getPermissionsForUser(org.cagrid.gaards.csm.stubs.GetPermissionsForUserRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.GetPermissionsForUserResponse boxedResult = new org.cagrid.gaards.csm.stubs.GetPermissionsForUserResponse();
    boxedResult.setPermission(impl.getPermissionsForUser(params.getApplicationId(),params.getUserIdentity()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.GetPermissionForGroupResponse getPermissionForGroup(org.cagrid.gaards.csm.stubs.GetPermissionForGroupRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.GetPermissionForGroupResponse boxedResult = new org.cagrid.gaards.csm.stubs.GetPermissionForGroupResponse();
    boxedResult.setPermission(impl.getPermissionForGroup(params.getGroupId()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.GetParentProtectionGroupResponse getParentProtectionGroup(org.cagrid.gaards.csm.stubs.GetParentProtectionGroupRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.GetParentProtectionGroupResponse boxedResult = new org.cagrid.gaards.csm.stubs.GetParentProtectionGroupResponse();
    boxedResult.setProtectionGroup(impl.getParentProtectionGroup(params.getChildProtectionGroupId()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.CheckPermissionResponse checkPermission(org.cagrid.gaards.csm.stubs.CheckPermissionRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.CheckPermissionResponse boxedResult = new org.cagrid.gaards.csm.stubs.CheckPermissionResponse();
    boxedResult.setResponse(impl.checkPermission(params.getApplicationId(),params.getUserIdentity(),params.getObjectId(),params.getPrivilege()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.CheckAttributeBasedPermissionResponse checkAttributeBasedPermission(org.cagrid.gaards.csm.stubs.CheckAttributeBasedPermissionRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.CheckAttributeBasedPermissionResponse boxedResult = new org.cagrid.gaards.csm.stubs.CheckAttributeBasedPermissionResponse();
    boxedResult.setResponse(impl.checkAttributeBasedPermission(params.getApplicationId(),params.getUserIdentity(),params.getObjectId(),params.getAttributeName(),params.getAttributeValue(),params.getPrivilege()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.CreateFilterClauseResponse createFilterClause(org.cagrid.gaards.csm.stubs.CreateFilterClauseRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.CreateFilterClauseResponse boxedResult = new org.cagrid.gaards.csm.stubs.CreateFilterClauseResponse();
    boxedResult.setFilterClause(impl.createFilterClause(params.getFilter().getFilterClause()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.ModifyFilterClauseResponse modifyFilterClause(org.cagrid.gaards.csm.stubs.ModifyFilterClauseRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.ModifyFilterClauseResponse boxedResult = new org.cagrid.gaards.csm.stubs.ModifyFilterClauseResponse();
    boxedResult.setFilterClause(impl.modifyFilterClause(params.getFilterClauseId(),params.getSqlForGroup(),params.getSqlForUser()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.GetFilterClausesResponse getFilterClauses(org.cagrid.gaards.csm.stubs.GetFilterClausesRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.GetFilterClausesResponse boxedResult = new org.cagrid.gaards.csm.stubs.GetFilterClausesResponse();
    boxedResult.setFilterClause(impl.getFilterClauses(params.getCriteria().getFilterClauseSearchCriteria()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.RemoveFilterClauseResponse removeFilterClause(org.cagrid.gaards.csm.stubs.RemoveFilterClauseRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault {
    org.cagrid.gaards.csm.stubs.RemoveFilterClauseResponse boxedResult = new org.cagrid.gaards.csm.stubs.RemoveFilterClauseResponse();
    impl.removeFilterClause(params.getFilterClauseId());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.CreateFilterCreatorResponse createFilterCreator(org.cagrid.gaards.csm.stubs.CreateFilterCreatorRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.HibernateSessionCreationFault {
    org.cagrid.gaards.csm.stubs.CreateFilterCreatorResponse boxedResult = new org.cagrid.gaards.csm.stubs.CreateFilterCreatorResponse();
    boxedResult.setFilterCreatorReference(impl.createFilterCreator(params.getApplicationID(),params.getApplicationBeansJar(),params.getApplicationORMJar(),params.getHibernateConfig()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.CreateFilterCreatorFromDomainModelResponse createFilterCreatorFromDomainModel(org.cagrid.gaards.csm.stubs.CreateFilterCreatorFromDomainModelRequest params) throws RemoteException {
    org.cagrid.gaards.csm.stubs.CreateFilterCreatorFromDomainModelResponse boxedResult = new org.cagrid.gaards.csm.stubs.CreateFilterCreatorFromDomainModelResponse();
    boxedResult.setFilterCreatorReference(impl.createFilterCreatorFromDomainModel(params.getApplicationID(),params.getDomainModel().getDomainModel()));
    return boxedResult;
  }

}
