package org.cagrid.workflow.helper.invocation.service;

import java.rmi.RemoteException;

import javax.naming.InitialContext;

import org.apache.axis.MessageContext;
import org.cagrid.workflow.helper.service.WorkflowHelperConfiguration;
import org.globus.wsrf.Constants;
import org.globus.wsrf.ResourceHome;


/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * Provides some simple accessors for the Impl.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public abstract class WorkflowInvocationHelperImplBase {
	
	public WorkflowInvocationHelperImplBase() throws RemoteException {
	
	}
	
	public WorkflowHelperConfiguration getConfiguration() throws Exception {
		return WorkflowHelperConfiguration.getConfiguration();
	}
	
	
	public org.cagrid.workflow.helper.invocation.service.globus.resource.WorkflowInvocationHelperResourceHome getResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("home");
		return (org.cagrid.workflow.helper.invocation.service.globus.resource.WorkflowInvocationHelperResourceHome)resource;
	}

	
	
	
	public org.cagrid.workflow.helper.service.globus.resource.WorkflowHelperResourceHome getWorkflowHelperResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("workflowHelperHome");
		return (org.cagrid.workflow.helper.service.globus.resource.WorkflowHelperResourceHome)resource;
	}
	
	public org.cagrid.workflow.helper.instance.service.globus.resource.WorkflowInstanceHelperResourceHome getWorkflowInstanceHelperResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("workflowInstanceHelperHome");
		return (org.cagrid.workflow.helper.instance.service.globus.resource.WorkflowInstanceHelperResourceHome)resource;
	}
	
	
	protected ResourceHome getResourceHome(String resourceKey) throws Exception {
		MessageContext ctx = MessageContext.getCurrentContext();

		ResourceHome resourceHome = null;
		
		String servicePath = ctx.getTargetService();

		String jndiName = Constants.JNDI_SERVICES_BASE_NAME + servicePath + "/" + resourceKey;
		try {
			javax.naming.Context initialContext = new InitialContext();
			resourceHome = (ResourceHome) initialContext.lookup(jndiName);
		} catch (Exception e) {
			throw new Exception("Unable to instantiate resource home. : " + resourceKey, e);
		}

		return resourceHome;
	}


}

