package org.cagrid.introduce.service4.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.1
 * 
 */
public interface Service4I {

  public java.lang.String securePrintResults(java.lang.String result1,java.lang.String result2) throws RemoteException ;

  public java.lang.String printResults(java.lang.String result1,java.lang.String result2) throws RemoteException ;

}

