package org.cagrid.introduce.service1.service.globus;

import org.cagrid.introduce.service1.service.Service1Impl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the Service1Impl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.1
 * 
 */
public class Service1ProviderImpl{
	
	Service1Impl impl;
	
	public Service1ProviderImpl() throws RemoteException {
		impl = new Service1Impl();
	}
	

    public org.cagrid.introduce.service1.stubs.GenerateDataResponse generateData(org.cagrid.introduce.service1.stubs.GenerateDataRequest params) throws RemoteException {
    org.cagrid.introduce.service1.stubs.GenerateDataResponse boxedResult = new org.cagrid.introduce.service1.stubs.GenerateDataResponse();
    boxedResult.setStringAndItsLenght(impl.generateData(params.getInfo()));
    return boxedResult;
  }

}
