package org.cagrid.workflow.test.validateoutputsservice.service.globus;

import org.cagrid.workflow.test.validateoutputsservice.service.ValidateOutputsServiceImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the ValidateOutputsServiceImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class ValidateOutputsServiceProviderImpl{
	
	ValidateOutputsServiceImpl impl;
	
	public ValidateOutputsServiceProviderImpl() throws RemoteException {
		impl = new ValidateOutputsServiceImpl();
	}
	

    public org.cagrid.workflow.test.validateoutputsservice.stubs.SecureValidateTestOutputResponse secureValidateTestOutput(org.cagrid.workflow.test.validateoutputsservice.stubs.SecureValidateTestOutputRequest params) throws RemoteException {
    org.cagrid.workflow.test.validateoutputsservice.stubs.SecureValidateTestOutputResponse boxedResult = new org.cagrid.workflow.test.validateoutputsservice.stubs.SecureValidateTestOutputResponse();
    impl.secureValidateTestOutput(params.getTest1Param1(),params.getTest1Param2().getComplexType(),params.isTest1Param3(),params.getTest2Param1(),params.getTest2Param2(),params.isTest2Param3(),params.getTest3Param1(),params.getTest3Param2());
    return boxedResult;
  }

    public org.cagrid.workflow.test.validateoutputsservice.stubs.ValidateTestOutputResponse validateTestOutput(org.cagrid.workflow.test.validateoutputsservice.stubs.ValidateTestOutputRequest params) throws RemoteException {
    org.cagrid.workflow.test.validateoutputsservice.stubs.ValidateTestOutputResponse boxedResult = new org.cagrid.workflow.test.validateoutputsservice.stubs.ValidateTestOutputResponse();
    impl.validateTestOutput(params.getTest1Param1(),params.getTest1Param2().getComplexType(),params.isTest1Param3(),params.getTest2Param1(),params.getTest2Param2(),params.isTest2Param3(),params.getTest3Param1(),params.getTest3Param2());
    return boxedResult;
  }

}
