package org.cagrid.redcap.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface RedcapDataServiceConstantsBase {
	public static final String SERVICE_NS = "http://redcap.cagrid.org/RedcapDataService";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "RedcapDataServiceKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "RedcapDataServiceResourceProperties");
	public static final QName SERVICEMETADATA = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata", "ServiceMetadata");
	public static final QName DOMAINMODEL = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata.dataservice", "DomainModel");
	
}
