/**
*============================================================================
*  The Ohio State University Research Foundation, Emory University,
*  the University of Minnesota Supercomputing Institute
*
*  Distributed under the OSI-approved BSD 3-Clause License.
*  See http://ncip.github.com/cagrid-grid-incubation/LICENSE.txt for details.
*============================================================================
**/
/**
*============================================================================
*============================================================================
**/
/**
 * This package provides annotations to allow interface writers to 
 * customize the operations generated by Introduce. The naming 
 * conventions used in this package are based on JSR 181 (the 
 * javax.jws package). 
 */
package edu.umn.msi.cagrid.introduce.interfaces.client;
