/**
*============================================================================
*  Copyright The Ohio State University Research Foundation, The University of Chicago - 
*	Argonne National Laboratory, Emory University, SemanticBits LLC, and 
*	Ekagra Software Technologies Ltd.
*
*  Distributed under the OSI-approved BSD 3-Clause License.
*  See http://ncip.github.com/cagrid-core/LICENSE.txt for details.
*============================================================================
**/
/**
 * This package provides annotations to allow interface writers to 
 * customize the operations generated by Introduce. The naming 
 * conventions used in this package are based on JSR 181 (the 
 * javax.jws package). 
 */
package edu.umn.msi.cagrid.introduce.interfaces.client;
