package org.cagrid.introduce.receivearrayservice.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.1
 * 
 */
public interface ReceiveArrayServiceI {

  public void receiveArray(java.lang.String[] arrayStr) throws RemoteException ;

  public void receiveArrayAndMore(int number,java.lang.String[] strArray,boolean booleanValue) throws RemoteException ;

  public void receiveComplexArray(int number,org.cagrid.workflow.systemtests.types.ComplexType[] complexArray,boolean booleanValue) throws RemoteException ;

  public void secureReceiveArray(java.lang.String[] arrayStr) throws RemoteException ;

  public void secureReceiveArrayAndMore(int number,java.lang.String[] strArray,boolean booleanValue) throws RemoteException ;

  public void secureReceiveComplexArray(int number,org.cagrid.workflow.systemtests.types.ComplexType[] complexArray,boolean booleanValue) throws RemoteException ;

}

