/*
============================================================================
  The Ohio State University Research Foundation, Emory University,
  the University of Minnesota Supercomputing Institute

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/cagrid-grid-incubation/LICENSE.txt for details.
============================================================================
*/
INSERT INTO I2B2DEMODATA.RESEARCH_TYPE (RESEARCH_TYPE_CD, RESEARCH_TYPE_DESC, CREATE_USER, CREATE_DATE) 
VALUES ('C','Clinical','DEFAULT','01-Jan-2010');

INSERT INTO I2B2DEMODATA.RESEARCH_TYPE (RESEARCH_TYPE_CD, RESEARCH_TYPE_DESC, CREATE_USER, CREATE_DATE) 
VALUES ('O','Observational','DEFAULT','01-Jan-2010');

INSERT INTO I2B2DEMODATA.RESEARCH_TYPE (RESEARCH_TYPE_CD, RESEARCH_TYPE_DESC, CREATE_USER, CREATE_DATE) 
VALUES ('A','Animal','DEFAULT','01-Jan-2010');

INSERT INTO I2B2DEMODATA.RESEARCH_TYPE (RESEARCH_TYPE_CD, RESEARCH_TYPE_DESC, CREATE_USER, CREATE_DATE) 
VALUES ('I','In vitro','DEFAULT','01-Jan-2010');

INSERT INTO I2B2DEMODATA.IRB_APPROVAL_TYPE (IRB_APPROVAL_TYPE_CD, IRB_APPROVAL_TYPE_DESC, CREATE_USER, CREATE_DATE) 
VALUES ('F','Full review','DEFAULT','01-Jan-2010');

INSERT INTO I2B2DEMODATA.IRB_APPROVAL_TYPE (IRB_APPROVAL_TYPE_CD, IRB_APPROVAL_TYPE_DESC, CREATE_USER, CREATE_DATE) 
VALUES ('E','Expedited review','DEFAULT','01-Jan-2010');

INSERT INTO I2B2DEMODATA.IRB_APPROVAL_TYPE (IRB_APPROVAL_TYPE_CD, IRB_APPROVAL_TYPE_DESC, CREATE_USER, CREATE_DATE) 
VALUES ('X','Exempt','DEFAULT','01-Jan-2010');

INSERT INTO I2B2DEMODATA.REQUEST_STATUS (REQUEST_STATUS_CD, REQUEST_STATUS_DESC, CREATE_USER, CREATE_DATE) 
VALUES ('P','Pending','DEFAULT','01-Jan-2010');

INSERT INTO I2B2DEMODATA.REQUEST_STATUS (REQUEST_STATUS_CD, REQUEST_STATUS_DESC, CREATE_USER, CREATE_DATE) 
VALUES ('I','In Process','DEFAULT','01-Jan-2010');

INSERT INTO I2B2DEMODATA.REQUEST_STATUS (REQUEST_STATUS_CD, REQUEST_STATUS_DESC, CREATE_USER, CREATE_DATE) 
VALUES ('C','Completed','DEFAULT','01-Jan-2010');

INSERT INTO I2B2DEMODATA.REQUEST_STATUS (REQUEST_STATUS_CD, REQUEST_STATUS_DESC, CREATE_USER, CREATE_DATE) 
VALUES ('O','On Hold','DEFAULT','01-Jan-2010');

INSERT INTO I2B2DEMODATA.REQUEST_STATUS (REQUEST_STATUS_CD, REQUEST_STATUS_DESC, CREATE_USER, CREATE_DATE) 
VALUES ('X','Cancelled','DEFAULT','01-Jan-2010');

INSERT INTO I2B2DEMODATA.MAP_TYPE (MAP_TYPE_CD, MAP_TYPE_DESC, CREATE_USER, CREATE_DATE) values ('ON','OnetoOne','DEFAULT','01-Jan-2010');

INSERT INTO I2B2DEMODATA.MAP_TYPE (MAP_TYPE_CD, MAP_TYPE_DESC, CREATE_USER, CREATE_DATE) values ('AG','Aggregate','DEFAULT','01-Jan-2010');

INSERT INTO I2B2DEMODATA.MAP_TYPE (MAP_TYPE_CD, MAP_TYPE_DESC, CREATE_USER, CREATE_DATE) values ('AR','Archetype','DEFAULT','01-Jan-2010');

COMMIT;
