package org.cagrid.mdrq.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface MDRQueryConstantsBase {
	public static final String SERVICE_NS = "http://mdrq.cagrid.org/MDRQuery";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "MDRQueryKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "MDRQueryResourceProperties");
	public static final QName RESOURCES = new QName("http://cagrid.org/schema/config", "resources");
	
}
